import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { SessionProvider } from 'next-auth/react'
import { Toaster } from "@/components/ui/sonner"
import ModalContainer from '@/components/modal/ModalContainer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionProvider>
    <html lang="en">
      <body >
     
        <Toaster   />
        <Navbar/>
        <ModalContainer/>

        <main className='my-[5rem] '>
        {children}
        </main>
     
   
        </body>
    </html>
    </SessionProvider>
  )
}
